
const GOOGLE_API_KEY = process.env.REACT_APP_GOOGLE_API_KEY

export const YOUTUBE_VIDEO_URL = process.env.REACT_APP_VIDEO_URL+GOOGLE_API_KEY;

export const YOUTUBE_SEARCH_URL = process.env.REACT_APP_YOUTUBE_SEARCH
